general:
  raw_data: False                    
  offline_datafile: './experience.h5'           # Path to .h5 file with offline data
  prefill: 50000
  device: cuda
  dtype: float32
  encoding_size: 
  run_name: 
  buffer_capacity: 10000000
  enc_input_size: 64             # Change to a more unambiguous parameter name
  enc_out_size: 4
  similar: 2
  rollout_enc_size: 4

atari:
  frame_size: [128, 128]
  action_repeat: 4
  grayscale: False
  noops: 30
  life_done: False
  sticky_actions: True
  all_actions: True

kmeans: 
  n_clusters: 8
  init: k-means++
  n_init: 10
  max_iter: 300
  tol: 1e-4
  verbose: False
  random_state: 
  copy_x: True
  algorithm: auto

dreamer:
  deter_dim: 2048
  stoch_dim: 32
  stoch_discrete: 32
  hidden_dim: 1000   # Does this have something to do with enc output shape?
  gru_layers: 1
  gru_type: gru
  layer_norm: True
  image_encoder: cnn
  cnn_depth: 48
  image_encoder_layers: 0
  image_decoder: cnn
  image_decoder_layers: 0
  reward_input: False
  reward_decoder_layers: 4
  reward_decoder_categorical: 
  terminal_decoder_layers: 4
  map_stoch_dim: 64
  map_model: none
  map_decoder: dense
  map_hidden_layers: 4
  map_hidden_dim: 1024
  map_channels: 4
  map_size: 11
  mem_model: none
  mem_loss_type: 

  # Actor Critic
  ac_gamma: 0.995
  lambda_gae: 0.95
  target_interval: 100
  imag_horizon: 15
  actor_grad: reinforce
  actor_dist: onehot

  # Training
  kl_weight: 1.0
  kl_balance: 0.8


  # Generator
  generator_wokers: 4
  generator_workers_eval: 1
  generator_prefill_steps: 200000
  generator_prefill_policy: random
  limit_step_ratio: 0
  env_id:
  env_id_eval:
  env_action_repeat: 1
  env_time_limit: 0
  env_no_terminal: False

dqn:
  hidden_layers: [64, 64]
  model_activation: relu
  model_dropout: 0.0
  gamma: 0.99
  epsilon: 0.2
  batch_size: 64
  tau: 0.99